from enums import Cols
import pandas as pd

mock_gradebook_df = pd.DataFrame([
    {
        Cols.StudentLastname.value: "test",
        Cols.StudentFirstname.value: "test",
        Cols.StudentId.value: "test",
        Cols.SchoolId.value: "test",
        Cols.TeacherLastname.value: "One",
        Cols.TeacherFirstname.value: "Teacher",
        Cols.TeacherFullname.value: "Teacher 1",
        Cols.StudentId.value: "test",
        Cols.GradeLevel.value: "test",
        Cols.AssignedDate.value: "test",
        Cols.AssignmentDue.value: "test",
        Cols.GradeEnteredOn.value: "test",

        Cols.ClassName.value: "Class 1",
        Cols.AssignmentName.value: "Assignment 1",
        Cols.CategoryName.value: "Category 1",
        Cols.CategoryWeight.value: 50,
        Cols.Score.value: 50,
        Cols.ScorePossible.value: 100
    },
    {
        Cols.StudentLastname.value: "test",
        Cols.StudentFirstname.value: "test",
        Cols.StudentId.value: "test",
        Cols.SchoolId.value: "test",
        Cols.TeacherLastname.value: "One",
        Cols.TeacherFirstname.value: "Teacher",
        Cols.TeacherFullname.value: "Teacher 1",
        Cols.StudentId.value: "test",
        Cols.GradeLevel.value: "test",
        Cols.AssignedDate.value: "test",
        Cols.AssignmentDue.value: "test",
        Cols.GradeEnteredOn.value: "test",

        Cols.ClassName.value: "Class 1",
        Cols.AssignmentName.value: "Assignment 1",
        Cols.CategoryName.value: "Category 1",
        Cols.CategoryWeight.value: 50,
        Cols.Score.value: 25,
        Cols.ScorePossible.value: 100
    },
    {
        Cols.StudentLastname.value: "test",
        Cols.StudentFirstname.value: "test",
        Cols.StudentId.value: "test",
        Cols.SchoolId.value: "test",
        Cols.TeacherLastname.value: "One",
        Cols.TeacherFirstname.value: "Teacher",
        Cols.TeacherFullname.value: "Teacher 1",
        Cols.StudentId.value: "test",
        Cols.GradeLevel.value: "test",
        Cols.AssignedDate.value: "test",
        Cols.AssignmentDue.value: "test",
        Cols.GradeEnteredOn.value: "test",

        Cols.ClassName.value: "Class 1",
        Cols.AssignmentName.value: "Assignment 1",
        Cols.CategoryName.value: "Category 1",
        Cols.CategoryWeight.value: 50,
        Cols.Score.value: 75,
        Cols.ScorePossible.value: 100
    },
    {
        Cols.StudentLastname.value: "weston",
        Cols.StudentFirstname.value: "test",
        Cols.StudentId.value: "tjaqwdst",
        Cols.SchoolId.value: "test",
        Cols.TeacherLastname.value: "One",
        Cols.TeacherFirstname.value: "Teacher",
        Cols.TeacherFullname.value: "Teacher 1",
        Cols.StudentId.value: "test",
        Cols.GradeLevel.value: "test",
        Cols.AssignedDate.value: "test",
        Cols.AssignmentDue.value: "test",
        Cols.GradeEnteredOn.value: "test",

        Cols.ClassName.value: "Class 1",
        Cols.AssignmentName.value: "Assignment 1",
        Cols.CategoryName.value: "Category 1",
        Cols.CategoryWeight.value: 50,
        Cols.Score.value: 0,
        Cols.ScorePossible.value: 100
    },
    {
        Cols.StudentLastname.value: "test",
        Cols.StudentFirstname.value: "snaggletooth",
        Cols.StudentId.value: "test",
        Cols.SchoolId.value: "test",
        Cols.TeacherLastname.value: "One",
        Cols.TeacherFirstname.value: "Teacher",
        Cols.TeacherFullname.value: "Teacher 1",
        Cols.StudentId.value: "test",
        Cols.GradeLevel.value: "test",
        Cols.AssignedDate.value: "test",
        Cols.AssignmentDue.value: "test",
        Cols.GradeEnteredOn.value: "test",

        Cols.ClassName.value: "Class 1",
        Cols.AssignmentName.value: "Assignment 1",
        Cols.CategoryName.value: "Category 1",
        Cols.CategoryWeight.value: 50,
        Cols.Score.value: 100,
        Cols.ScorePossible.value: 100
    },
    {
        Cols.StudentLastname.value: "test",
        Cols.StudentFirstname.value: "test",
        Cols.StudentId.value: "test",
        Cols.SchoolId.value: "test",
        Cols.TeacherLastname.value: "One",
        Cols.TeacherFirstname.value: "Teacher",
        Cols.TeacherFullname.value: "Teacher 1",
        Cols.StudentId.value: "test",
        Cols.GradeLevel.value: "test",
        Cols.AssignedDate.value: "test",
        Cols.AssignmentDue.value: "test",
        Cols.GradeEnteredOn.value: "test",

        Cols.ClassName.value: "Class 2",
        Cols.AssignmentName.value: "Assignment 1",
        Cols.CategoryName.value: "Category 1",
        Cols.CategoryWeight.value: 50,
        Cols.Score.value: "A",
        Cols.ScorePossible.value: 100
    },
    {
        Cols.StudentLastname.value: "test",
        Cols.StudentFirstname.value: "test",
        Cols.StudentId.value: "test",
        Cols.SchoolId.value: "test",
        Cols.TeacherLastname.value: "One",
        Cols.TeacherFirstname.value: "Teacher",
        Cols.TeacherFullname.value: "Teacher 1",
        Cols.StudentId.value: "test",
        Cols.GradeLevel.value: "test",
        Cols.AssignedDate.value: "test",
        Cols.AssignmentDue.value: "test",
        Cols.GradeEnteredOn.value: "test",

        Cols.ClassName.value: "Class 2",
        Cols.AssignmentName.value: "Assignment 1",
        Cols.CategoryName.value: "Category 1",
        Cols.CategoryWeight.value: 50,
        Cols.Score.value: "B",
        Cols.ScorePossible.value: 100
    },
    {
        Cols.StudentLastname.value: "test",
        Cols.StudentFirstname.value: "test",
        Cols.StudentId.value: "test",
        Cols.SchoolId.value: "test",
        Cols.TeacherLastname.value: "One",
        Cols.TeacherFirstname.value: "Teacher",
        Cols.TeacherFullname.value: "Teacher 1",
        Cols.StudentId.value: "test",
        Cols.GradeLevel.value: "test",
        Cols.AssignedDate.value: "test",
        Cols.AssignmentDue.value: "test",
        Cols.GradeEnteredOn.value: "test",

        Cols.ClassName.value: "Class 2",
        Cols.AssignmentName.value: "Assignment 1",
        Cols.CategoryName.value: "Category 1",
        Cols.CategoryWeight.value: 50,
        Cols.Score.value: "C",
        Cols.ScorePossible.value: 100
    },
    {
        Cols.StudentLastname.value: "weston",
        Cols.StudentFirstname.value: "test",
        Cols.StudentId.value: "tjaqwdst",
        Cols.SchoolId.value: "test",
        Cols.TeacherLastname.value: "One",
        Cols.TeacherFirstname.value: "Teacher",
        Cols.TeacherFullname.value: "Teacher 1",
        Cols.StudentId.value: "test",
        Cols.GradeLevel.value: "test",
        Cols.AssignedDate.value: "test",
        Cols.AssignmentDue.value: "test",
        Cols.GradeEnteredOn.value: "test",

        Cols.ClassName.value: "Class 2",
        Cols.AssignmentName.value: "Assignment 1",
        Cols.CategoryName.value: "Category 1",
        Cols.CategoryWeight.value: 50,
        Cols.Score.value: "D",
        Cols.ScorePossible.value: 100
    },
    {
        Cols.StudentLastname.value: "test",
        Cols.StudentFirstname.value: "snaggletooth",
        Cols.StudentId.value: "test",
        Cols.SchoolId.value: "test",
        Cols.TeacherLastname.value: "One",
        Cols.TeacherFirstname.value: "Teacher",
        Cols.TeacherFullname.value: "Teacher 1",
        Cols.StudentId.value: "test",
        Cols.GradeLevel.value: "test",
        Cols.AssignedDate.value: "test",
        Cols.AssignmentDue.value: "test",
        Cols.GradeEnteredOn.value: "test",

        Cols.ClassName.value: "Class 2",
        Cols.AssignmentName.value: "Assignment 1",
        Cols.CategoryName.value: "Category 1",
        Cols.CategoryWeight.value: 50,
        Cols.Score.value: "Msg",
        Cols.ScorePossible.value: 100
    },
    {
        Cols.StudentLastname.value: "test",
        Cols.StudentFirstname.value: "snaggletooth",
        Cols.StudentId.value: "test",
        Cols.SchoolId.value: "test",
        Cols.TeacherLastname.value: "One",
        Cols.TeacherFirstname.value: "Teacher",
        Cols.TeacherFullname.value: "Teacher 1",
        Cols.StudentId.value: "test",
        Cols.GradeLevel.value: "test",
        Cols.AssignedDate.value: "test",
        Cols.AssignmentDue.value: "test",
        Cols.GradeEnteredOn.value: "test",

        Cols.ClassName.value: "Class 2",
        Cols.AssignmentName.value: "Assignment 1",
        Cols.CategoryName.value: "Category 1",
        Cols.CategoryWeight.value: 50,
        Cols.Score.value: "",
        Cols.ScorePossible.value: 100
    },
    {
        Cols.StudentLastname.value: "test",
        Cols.StudentFirstname.value: "snaggletooth",
        Cols.StudentId.value: "test",
        Cols.SchoolId.value: "test",
        Cols.TeacherLastname.value: "One",
        Cols.TeacherFirstname.value: "Teacher",
        Cols.TeacherFullname.value: "Teacher 1",
        Cols.StudentId.value: "test",
        Cols.GradeLevel.value: "test",
        Cols.AssignedDate.value: "test",
        Cols.AssignmentDue.value: "test",
        Cols.GradeEnteredOn.value: "test",

        Cols.ClassName.value: "Class 2",
        Cols.AssignmentName.value: "Assignment 1",
        Cols.CategoryName.value: "Category 1",
        Cols.CategoryWeight.value: 50,
        Cols.Score.value: "Inc",
        Cols.ScorePossible.value: 100
    },
    {
        Cols.StudentLastname.value: "test",
        Cols.StudentFirstname.value: "snaggletooth",
        Cols.StudentId.value: "test",
        Cols.SchoolId.value: "test",
        Cols.TeacherLastname.value: "One",
        Cols.TeacherFirstname.value: "Teacher",
        Cols.TeacherFullname.value: "Teacher 1",
        Cols.StudentId.value: "test",
        Cols.GradeLevel.value: "test",
        Cols.AssignedDate.value: "test",
        Cols.AssignmentDue.value: "test",
        Cols.GradeEnteredOn.value: "test",

        Cols.ClassName.value: "Class 2",
        Cols.AssignmentName.value: "Assignment 1",
        Cols.CategoryName.value: "Category 1",
        Cols.CategoryWeight.value: 50,
        Cols.Score.value: "Exc",
        Cols.ScorePossible.value: 100
    },
])


mock_gradebook_df_aggregated_assignments = pd.DataFrame([
    {
        Cols.SchoolId.value: "test",
        Cols.TeacherLastname.value: "One",
        Cols.TeacherFirstname.value: "Teacher",
        Cols.TeacherFullname.value: "Teacher 1",
        Cols.GradeLevel.value: "test",
        Cols.AssignedDate.value: "test",
        Cols.AssignmentDue.value: "test",
        Cols.GradeEnteredOn.value: "test",

        Cols.ClassName.value: "Class 1",
        Cols.AssignmentName.value: "Assignment 1",
        Cols.CategoryName.value: "Category 1",
        Cols.CategoryWeight.value: 50.0,
        Cols.Score.value: 50.0,
        Cols.ScorePossible.value: 100.0,

        "NumAssignments": 5.0,
        "NumMissing": 0.0,
        "NumIncomplete": 0.0,
        "NumExcused": 0.0,
        "NumZero": 1.0,
        "NumBlank": 0.0

    },
    {
        Cols.SchoolId.value: "test",
        Cols.TeacherLastname.value: "One",
        Cols.TeacherFirstname.value: "Teacher",
        Cols.TeacherFullname.value: "Teacher 1",
        Cols.GradeLevel.value: "test",
        Cols.AssignedDate.value: "test",
        Cols.AssignmentDue.value: "test",
        Cols.GradeEnteredOn.value: "test",

        Cols.ClassName.value: "Class 2",
        Cols.AssignmentName.value: "Assignment 1",
        Cols.CategoryName.value: "Category 1",
        Cols.CategoryWeight.value: 50.0,
        Cols.Score.value: 63.3,
        Cols.ScorePossible.value: 100.0,

        "NumAssignments": 8.0,
        "NumMissing": 1.0,
        "NumIncomplete": 1.0,
        "NumExcused": 1.0,
        "NumZero": 0.0,
        "NumBlank": 1.0
    }
])
